### ISSUE TITLE
全体管理

### ISSUE THREAD

**Issue by mukaida-r** [camp-team/okr-app#31]
## サービス紹介画面
- [x] サービス紹介画面 #32 
- [ ] サービス紹介内容 #50 
- [ ] サービス紹介画面レイアウト #91
- [x] ログイン機能 #33 
## 管理画面
- [x] 検索画面 #43
- [x] ログアウト機能 #34 
- [ ] 管理画面レイアウト #104 
## 入力画面(edit.module)
- [x] 入力画面 #36 
- [x] form機能 #37 
- [ ] 期間の範囲(カレンダーアプリと連携できるのか？ ) #38 
- [ ] 入力画面レイアウト #138 
## ホーム画面(home.module)
- [x] ホーム画面 #40
- [ ] ホーム画面レイアウト #58 
- [x] データベースから値を受け取る 
- [x] 詳細ボタン #29
- [ ] 要素の高さを揃える #92
- [ ] ドラックアンドドロップ実装 #118
## 編集画面(edit.module)
- [x] 目標詳細ボタン実装 #54
- [x] 配列の要素を初期値でセット #131
- [ ] 編集画面レイアウト #93
- [ ] 編集画面コンテンツ追加機能実装 #135
## 編集画面コンテンツの詳細ボタンの概要
- [ ] Google Sheets API　or  mat-tableに遷移 
- [ ] firestoreのデータのupdate実装 #44 
- [ ] firestoreのデータのdelate実装 #117 
- [ ] コンテンツのダイアログ実装 #94 
## Google Sheets API　or  mat-table画面
- [ ] テーブル概要概要({No、日付、項目、チェックリスト...etc} → データ計算)  #46
## コンテンツのダイアログの概要
- [ ] 詳細画面(内容：達成率、タイトル、変更日、ToDo機能(検討中)) #94
- [ ] 詳細画面レイアウト#95
- [ ] 達成率(%で計算し、表示する) #53 
- [ ] コンテンツの詳細画面に遷移
## コンテンツの詳細画面
- [ ] コンテンツの詳細画面レイアウト #132 
- [ ] コンテンツの詳細画面の内容(内容：達成率、タイトル、変更日、ToDo機能(検討中)) #133
## Example(検討中)
- [ ] Example画面の内容(目標の立て方、事例) #42
- [ ] Example画面レイアウト #134
## 検索
- [ ] Algolia #51  
## firebase
- [x] firebaseの環境構築
- [x] firebaseとAngularを連携する
## favicon
- [x] favicon #57  
## 404
- [x] 404ページ #52 
## 設定
- [ ] 退会機能 #45 
## 課金（優先度高）
- [ ] サブスク
- [ ] 課金画面 #96
- [ ] 課金機能 #97
## 利用規約
- [x] 利用規約画面
- [x] 利用規約の内容 #47 
- [ ] 利用規約の画面レイアウト #98
## 特定商取引法に基づく表記 
- [x] 特定商取引法に基づく表記の画面 #48
- [x] 特定商取引法に基づく表記の内容 #47 
- [ ] 特定商取引法に基づく表記の外面レイアウト #100
## プライバシーポリシーとセキュリティ 
- [x] プライバシーポリシーページ #49
- [ ] プライバシーポリシーページ内容 #101
- [ ] プライバシーポリシーページ画面レイアウト #102
## レスポンシブ対応
- [ ] レスポンシブ対応 #103
## 検討中
- [ ] OKRをチームで共有
- [ ] 各コンテンツにドラックアンドドロップ機能を持たせる（達成できなかったコンテンツを管理する。）
- [ ] ToDoをSNSに投稿
- [ ] OKR(達成した目標)の教材化
## ディレクトリ構造・DB構造
<img width="805" alt="スクリーンショット 2020-11-11 1 58 50" src="https://user-images.githubusercontent.com/61979156/98705807-74319980-23c1-11eb-8de3-97ffbdb86c72.png">

## ファイル
<img width="408" alt="スクリーンショット 2020-11-11 1 57 46" src="https://user-images.githubusercontent.com/61979156/98705670-4d736300-23c1-11eb-9b39-83e71d1b72d3.png">
